### ISSUE TITLE
Argument manual.lookup in import.q.sorts & *feedback (and arg. conditions)

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#118] opened 2015-03-19 19:31 UTC
I think that we're almost there, @maxheld83 Can you please take a look at these?
- (important) Argument `manual.lookup` in `import.q.sorts, import.q.feedback` seems to need a value, otherwise returns error. If it *requires* a value, then default cannot be `NULL` and should be left empty (default can't be something that would give an error), i.e should be:
```{r}
import.q.sorts(
  	q.sorts.dir,
		q.set,
		q.distribution,
		conditions = NULL,
		manual.lookup
	)
```
It could also be that it's not clear from the documentation (in which case would `NULL` *not* give an error?), or simply add a default behaviour (:?)
- (suggestion) In `import.q.sorts()`, add a warning or stop if `conditions` are set but there are no folders with these conditions (which returns an empty array)

**Comment by maxheld83** [comment] 2015-03-19 20:32
yes! on it

**Comment by maxheld83** [comment] 2015-03-19 21:21
**re: empty `manual.lookup` in `import.q.sorts` and `import.q.feedback`**

@aiorazabala I am not sure I got this right and/or can reproduce.

I *think* the error you're seeing is something like this:

```
Error in import.q.sorts(q.sorts.dir = "keyneson/qsorts/", q.set = q_set,  : 
The qsort in keyneson/qsorts/before/Christian.csv contains id c57 not defined in the lookup table.
```

This is actually *intended* behavior: what happened is just that *no* **manual.lookup** was specified, therefore the function was looking for *automatic*/*hashed* IDs in the CSV.
Because there *were* no automatic/hashed IDs in the CSV, the function returns an error for the first item it tries to read in, but cannot, because the ID is unknown.

It's possible that this might happen to people, and they might not find the error message very helpful.
I've added this friendly advisory to the error message, which hopefully clarifies this:

>   "Feedback in", path, "under id", id, "is not defined as per manual.lookup and was ignored.", "Check whether you defined manual.lookup argument as intended."

Is that the error you saw?
Does this make sense?

**Comment by maxheld83** [comment] 2015-03-19 22:17
re: @aiorazabala 
> (suggestion) In import.q.sorts(), add a warning or stop if conditions are set but there are no folders with these conditions (which returns an empty array)

Done!

**Comment by maxheld83** [comment] 2015-03-19 22:19
*if* I got the above error message right, this can now be closed.
@aiorazabala close this if you think it's done.
Changes pass `R CMD Check`, and are merged (they're tiny).

**Comment by aiorazabala** [comment] 2015-03-20 15:02
All good. The `import.q.sorts` might need more clarification for dummies in the future, but it all makes sense now.

**Comment by aiorazabala** [comment] 2015-03-20 15:03
Let me double check everything again before submitting to CRAN

**Comment by maxheld83** [comment] 2015-03-27 10:03
@aiorazabala let me know if there's anything left to do – hope I didn't miss anything.

**Closed** 2015-03-27 20:19 UTC
Labels: bug, documentation
