### ISSUE TITLE
Improve message error in import.q.sorts

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#310] opened 2015-10-09 04:22 UTC
In `import.q.sorts()` if the lookup table in `manual.lookup` is longer than it should be (e.g. 40 statements instead of 30), the function throws the following error

``` R
Error in current.sort[current.sort == id] <- handle : 
  replacement has length zero
```

Maybe add a line of code with an error message indicating that the reason for this error is that the `manual.lookup` might be wrong?

**Comment by maxheld83** [comment] 2015-10-09 11:11
will do!

**Comment by maxheld83** [comment] 2016-08-02 18:43
duplicate of https://github.com/maxheld83/pensieve/issues/94

**Closed** 2017-05-15 20:33 UTC
Labels: enhancement, import / cleaning
