### ISSUE TITLE
q.set in documentation of import.q.sorts

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#312] opened 2015-10-12 04:24 UTC
In the documentation of `import.q.sorts` where it says:

``` R
    \item{q.set}{
        A matrix with handles as row names, languages (if applicable) 
                in columns, as read in by \code{\link{build.q.set}}.
    }
```

Is it a matrix of full statements with handles as rownames?
Please indicate "a matrix of what", e.g. `A matrix of full statements with handles...`

**Comment by maxheld83** [comment] 2016-08-02 18:45
duplicate of https://github.com/maxheld83/pensieve/issues/95

**Closed** 2017-05-15 20:33 UTC
Labels: documentation, question
