### ISSUE TITLE
extracting many factors leads to cryptic error message

### ISSUE THREAD

**Issue by VerenaKasztantowicz** [aiorazabala/qmethod#72] opened 2015-02-19 21:22 UTC
I just tried to extract 7 factors from [my q study](https://github.com/VerenaKasztantowicz/wortweltihr) with 61 items and 37 participants:

```
wortweltihr <- qmethod(dataset = q.sorts, nfactors = 7, rotation = "varimax", forced = TRUE)
```

Oddly, I get the below error message:

```
Error in apply(wraw_all_flagged, 1, pop.sd) : 
dim(X) must have a positive length
```

7 factors might be too many for my study (6 works fine), but I'm not sure what this error means, or why it arises. Any thoughts?

P.S.: Thanks for the great package – this must have been so much work!

**Comment by maxheld83** [comment] 2015-02-19 21:23
uh, that is odd – not sure what that error message means, either.

I can reproduce the error with my data (77 items, 17 participants) - starting at **5** factors already.

**Comment by maxheld83** [comment] 2015-02-19 21:26
@aiorazabala It seems like I might have introduced this error `pop.sd` looks like my edit – I'll take care of this.

It's part of some of my branches (off which @VerenaKasztantowicz is working), but *not* the CRAN version, so this isn't strictly speaking a bug of `qmethod`.

I'll assign this to myself.

**Comment by maxheld83** [comment] 2015-02-20 08:27
ok, I got it: this turned out to be an error introduced by these lines of mine (for #66):

```
# here comes the sd across all sorts flagged on a factor
    wraw_all_flagged <- wraw_all[[n]][,which(!apply(wraw_all[[n]]==0,2,all))]  # chose only flagged, drop must be FALSE in case there is only one flagged, which causes errors downstream
    item_sd[,n] <- apply(wraw_all_flagged,1,pop.sd) # make pop sd
```

In the rare (and problematic) case where only *one* sort was flagged for a factor, the subsetting operation `wraw_all[[n]][,which(!apply(wraw_all[[n]]==0,2,all))]` produces a vector, not a matrix (dropping redundant dimensions).
The `apply` function then errors out, because it expects a matrix, not a vector.
I fixed this by adding `[..., drop=FALSE]` to the subsetting operation, as [recommended](http://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-do-my-matrices-lose-dimensions_003f) by the R FAQ.

thanks @VerenaKasztantowicz for reporting this!

Ps.: I like how the R FAQ refers to this behavior:

>  After much discussion this has been determined to be a *feature*.

**Closed by maxheld83** 2015-02-20 08:27 UTC
Labels: analysis, bug, extraction
