### ISSUE TITLE
include examples for image-based make.cards

### ISSUE THREAD

**Issue by VerenaKasztantowicz** [aiorazabala/qmethod#320] opened 2015-10-27 17:33 UTC
would be nice to have examples and/or a vignette so people can easily figure out how to supply images to `make.cards()` as per #296

**Comment by maxheld83** [comment] 2016-08-02 18:46
duplicate of https://github.com/maxheld83/pensieve/issues/98

**Closed** 2017-05-15 20:33 UTC
Labels: administration
