### ISSUE TITLE
import.q.sorts yields 0-max scale when distribution is free

### ISSUE THREAD

**Issue by VerenaHeld** [aiorazabala/qmethod#338] opened 2015-11-28 18:20 UTC
oddly, when `q.distribution=NULL`, `import.q.sorts` produces Q-sorts with values that range from 0 to max of values.

To some extend, this makes sense, because it's not clear around which value they should be centered, but still, it's surprising for the user.

**Comment by VerenaKasztantowicz** [comment] 2015-11-28 18:25
turns out, even if  headers are used and `header=TRUE`, import.q.sorts does not yield the correct values but always starts at 0

**Comment by maxheld83** [comment] 2015-11-29 14:47
yup, this is one of the free distro issues I have to fix

**Comment by maxheld83** [comment] 2015-11-29 14:48
luckily, the functions should still be somewhat usable, because downstream PCA standardizes values anyway ...

**Comment by maxheld83** [comment] 2016-08-02 18:52
duplicate of https://github.com/maxheld83/pensieve/issues/109

**Closed** 2021-02-23 02:54 UTC
Labels: administration
