### ISSUE TITLE
2 factor solutions cannot be colored automatically

### ISSUE THREAD

**Issue by VerenaKasztantowicz** [aiorazabala/qmethod#339] opened 2015-11-28 19:10 UTC
`minimal value for n is 3, returning requested palette with 3 different levels`

**Comment by maxheld83** [comment] 2015-11-29 14:48
uh that is a strange one.

**Comment by maxheld83** [comment] 2016-08-02 18:52
duplicate of https://github.com/maxheld83/pensieve/issues/110

**Closed** 2017-05-15 20:30 UTC
Labels: plots
